### ISSUE TITLE
Error in one of the Set methods in FileCacheExtensions

### ISSUE THREAD

**Issue by DrHeinzDoofenshmirtz** [ghominejad/AcroFS#1]
Hi.

I think I have found a problem.
You are missing a 
`cacheEntry.Dispose();`
in the `Set<TItem>(this FileCache cache, object key, TItem value, MemoryCacheEntryOptions options)`
which is present in all the other `Set` methods.

It is causing me a problem right now where it is failing to create the cached file.

At least, I believe that is the problem, as if I call the other `Set` methods, it works.

**Comment by ghominejad** [comment]
Thanks @DrHeinzDoofenshmirtz for flagging this issue. Can you please confirm if the error still exists? If it does, we'd appreciate if you could submit a PR with the fix. Thanks again!
